name: Deploy to Azure Container App

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Azure CLI configuration
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az extension add --name containerapp

      - name: Create or Update Container App
        run: |
          RESOURCE_GROUP="devsecops-lab"
          CONTAINER_APP_ENVIRONMENT="devops-app-env"
          CONTAINER_APP_NAME="devops-app"
          LOCATION="australiaeast"
          IMAGE="***/devops-labs:latest"
          TARGET_PORT=5000

          az containerapp show --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP || az containerapp create --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP --environment $CONTAINER_APP_ENVIRONMENT --image $IMAGE --target-port $TARGET_PORT --location $LOCATION

          az containerapp update --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP --image $IMAGE --ingress 'true' --target-port $TARGET_PORT
